# Generated by Django 5.0.6 on 2024-07-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='follow_ups',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
